# 参考：https://yoshinorin.net/articles/2021/02/23/ghaction-ghcr/

name: Publish Docker image test
on:
  push:
    # タグをpushしたら実行されるように
    tags:
      - 'v*.*.*'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        # メタ情報を取得してくれるaction, gitタグをdockerのタグで使用するために設定している
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/ogawa-tomohiro-jaxa/github-container-registry-test
      -
        # GitHub Container Registry にログインする
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}      # secretで作成したものを指定
      -
        # イメージビルドしてGitHub Container Registry に pushする
        name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          # Dokcerfileのパス
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}